init-properties:
  field:
    width: 5
    height: 5
  car-startposition:
    positionX: 0
    positionY: 0
    direction: NORTH
commands:
  left: повернуть налево
  right: повернуть направо
  move: проехать единицу дистанции
  left-sidestep: проехать налево
  turn-180degrees: повернуть на 180
parser-conf:
  default-filepath: src/main/resources/textCommands.txt
  use-separator: true
  separator: ;